### ISSUE TITLE
android.util.AndroidRuntimeException: requestFeature() must be called before adding content

### ISSUE THREAD

**Issue by 19chang19** [getActivity/Logcat#13]
引入库后，调用requestWindowFeature(Window.FEATURE_NO_TITLE);出错了     
Caused by: android.util.AndroidRuntimeException: requestFeature() must be called before adding content
        at com.android.internal.policy.PhoneWindow.requestFeature(PhoneWindow.java:334)
        at android.app.Activity.requestWindowFeature(Activity.java:3671)
        at com.msn.carlink.MainActivity.onCreate(MainActivity.java:150)

**Comment by getActivity** [comment]
小伙子，我这边在 Demo 上面的 `MainActivity.onCreate` 中加入 `requestWindowFeature(Window.FEATURE_NO_TITLE);` 这句代码没有任何问题，你这边看看是不是其他问题导致？
