### ISSUE TITLE
java.lang.NullPointerException 空指针问题

### ISSUE THREAD

**Issue by Vindac** [getActivity/Logcat#22]
#### 问题描述

* 框架版本【必填】：com.github.getActivity:Logcat:11.0

* 问题描述【必填】：如题，使用的悬浮布局模式，一点击图标就崩溃，使用通知栏模式没有问题

* 复现步骤【必填】：使用的悬浮布局模式，一点击图标就崩溃

* 是否必现【必填】：是

* 出现问题的手机信息【必填】：Google Pixel4 / Android13

* 出现问题的安卓版本【必填】：Android13

* 问题信息的来源渠道【必填】：Logcat调试日志

#### 请回答

* 是部分机型还是所有机型都会出现【必答】：全部

* 框架最新的版本是否存在这个问题【必答】：是

* 是否已经查阅框架文档还未能解决的【必答】：是

* issue 是否有人曾提过类似的问题【必答】：否

* 是否可以通过 Demo 来复现该问题【必答】：使用的DemoApp没有此问题

#### 其他

* 提供报错堆栈（如果有报错的话必填，注意不要拿被混淆过的代码堆栈上来）
*  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.pm.PackageManager android.content.Context.getPackageManager()' on a null object reference
        at com.hjq.logcat.LogcatUtils.getMetaStringData(LogcatUtils.java:104)
        at com.hjq.logcat.LogcatConfig.getSearchKeyConfig(LogcatConfig.java:48)
        at com.hjq.logcat.LogcatActivity.initSearchCondition(LogcatActivity.java:157)
        at com.hjq.logcat.LogcatActivity.onCreate(LogcatActivity.java:135)
        at android.app.Activity.performCreate(Activity.java:8290)
        at android.app.Activity.performCreate(Activity.java:8269)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1384)
* 
![image](https://user-images.githubusercontent.com/31061813/208840469-9e66e3dd-8b13-465a-8665-73267542cce1.png)

* 提供截图或视频（根据需要提供，此项不强制）

* 提供解决方案（如果已经解决了的话，此项不强制）

**Comment by Vindac** [comment]
<meta-data
            android:name="LogcatWindowEntrance"
            android:value="true" />
        
        <meta-data
            android:name="LogcatNotifyEntrance"
            android:value="true" />
            
两个都配置为true没问题，把通知栏设置成false就不行了

**Comment by getActivity** [comment]
小伙子，问题修复了，更新到 11.2 版本即可。
