### ISSUE TITLE
[Bug]：Unable to start service com.hjq.logcat.LogcatService@301b8a9 with Intent { cmp=com.hjq.logcat.demo/com.hjq.logcat.LogcatService }: java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000000 in service

### ISSUE THREAD

**Issue by 2002Wingfung** [getActivity/Logcat#38]
### 框架版本【必填】

11.85

### 问题描述【必填】

Android14打开你的app马上闪退

### 复现步骤【必填】

一打开app就报异常闪退

### 是否必现【必填】

是

### 项目 targetSdkVersion【必填】

34

### 出现问题的手机信息【必填】

三星S21

### 出现问题的安卓版本【必填】

14

### 问题信息的来源渠道【必填】

自己遇到的

### 是部分机型还是所有机型都会出现【必答】

三星G9910安卓14

### 框架最新的版本是否存在这个问题【必答】

是

### 框架文档是否提及了该问题【必答】

否

### 是否已经查阅框架文档但还未能解决的【必答】

未选择

### issue 列表中是否有人曾提过类似的问题【必答】

是

### 是否已经搜索过了 issue 列表但还未能解决的【必答】

是

### 是否可以通过 Demo 来复现该问题【必答】

否

### 提供报错堆栈

```text
FATAL EXCEPTION: main
                                                                                                    Process: com.hjq.logcat.demo, PID: 10797
                                                                                                    java.lang.RuntimeException: Unable to start service com.hjq.logcat.LogcatService@7a4ef86 with Intent { cmp=com.hjq.logcat.demo/com.hjq.logcat.LogcatService }: java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5286)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.IllegalArgumentException: foregroundServiceType 0x00000001 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3073)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:7214)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at leakcanary.ServiceWatcher$install$4$2.invoke(ServiceWatcher.kt:93)
                                                                                                    	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
                                                                                                    	at $Proxy3.setServiceForeground(Unknown Source)
                                                                                                    	at android.app.Service.startForeground(Service.java:862)
                                                                                                    	at com.hjq.logcat.LogcatService.onStartCommand(LogcatService.java:97)
                                                                                                    	at android.app.ActivityThread.handleServiceArgs(ActivityThread.java:5268)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleServiceArgs(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2531) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103) 
                                                                                                    Caused by: android.os.RemoteException: Remote stack trace:
                                                                                                    	at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:2171)
                                                                                                    	at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:1785)
                                                                                                    	at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:15850)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact$setServiceForeground$(IActivityManager.java:11873)
                                                                                                    	at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:3499)
```

**Comment by getActivity** [comment]
[Logcat-11.86.aar.zip](https://github.com/getActivity/Logcat/files/14329846/Logcat-11.86.aar.zip)

**Comment by getActivity** [comment]
@2002Wingfung 小伙子，问题修复了，你可以下载上面的 aar 包测试一下。

**Comment by getActivity** [comment]
* 另外需要注意加上 EasyWindow 的远程依赖，否则会出现运行报错

```groovy
dependencies {
    // 悬浮窗框架：https://github.com/getActivity/EasyWindow
    implementation 'com.github.getActivity:EasyWindow:10.6'
}
```

**Comment by 2002Wingfung** [comment]
加上了aar包和EasyWindow 远程依赖后出现异常：
FATAL EXCEPTION: main
                                                                                                    Process: com.topviewclub.crawling, PID: 6805
                                                                                                    java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/v4/app/NotificationManagerCompat;
                                                                                                    	at com.hjq.logcat.LogcatProvider.isNotificationChannelEnabled(LogcatProvider.java:92)
                                                                                                    	at com.hjq.logcat.LogcatProvider.onCreate(LogcatProvider.java:38)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2690)
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2660)
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8458)
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7963)
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7649)
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893)
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method)
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
                                                                                                    Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.v4.app.NotificationManagerCompat" on path: DexPathList[[dex file "/data/data/com.topviewclub.crawling/code_cache/.overlay/base.apk/classes.dex", dex file "/data/data/com.topviewclub.crawling/code_cache/.overlay/base.apk/classes13.dex", dex file "/data/data/com.topviewclub.crawling/code_cache/.overlay/base.apk/classes16.dex", dex file "/data/data/com.topviewclub.crawling/code_cache/.overlay/base.apk/classes17.dex", dex file "/data/data/com.topviewclub.crawling/code_cache/.overlay/base.apk/classes7.dex", zip file "/data/app/~~nuc7lCWMWwOn_8dxHp916g==/com.topviewclub.crawling-ytpnKPMbpqvL2MZFgszbeg==/base.apk"],nativeLibraryDirectories=[/data/app/~~nuc7lCWMWwOn_8dxHp916g==/com.topviewclub.crawling-ytpnKPMbpqvL2MZFgszbeg==/lib/arm64, /system/lib64, /system/system_ext/lib64]]
                                                                                                    	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:259)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
                                                                                                    	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
                                                                                                    	at com.hjq.logcat.LogcatProvider.isNotificationChannelEnabled(LogcatProvider.java:92) 
                                                                                                    	at com.hjq.logcat.LogcatProvider.onCreate(LogcatProvider.java:38) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2690) 
                                                                                                    	at android.content.ContentProvider.attachInfo(ContentProvider.java:2660) 
                                                                                                    	at android.app.ActivityThread.installProvider(ActivityThread.java:8458) 
                                                                                                    	at android.app.ActivityThread.installContentProviders(ActivityThread.java:7963) 
                                                                                                    	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7649) 
                                                                                                    	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0) 
                                                                                                    	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2478) 
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:106) 
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230) 
                                                                                                    	at android.os.Looper.loop(Looper.java:319) 
                                                                                                    	at android.app.ActivityThread.main(ActivityThread.java:8893) 
                                                                                                    	at java.lang.reflect.Method.invoke(Native Method) 
                                                                                                    	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608) 
                                                                                                    	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
